# Copyright 2022 <mzh.scnu@qq.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.


# The load balancing algorithms supported by the balancer are:
# `round-robin` ,`random` ,`p2c` ,`consistent-hash` ,`least-load` ,`bounded` ,`ip-hash`,
# Among these,`p2c` refers to the power of 2 random choice,
# `bounded` refers to consistent hash with bounded.
# commiunity-aware
port: 5091                    # port for balancer
location:                     # route matching for reverse proxy
  - proxy_pass:                   # URL of the reverse proxy
    - "49.52.27.77:8001"
    # - "49.52.27.77:18887"
    # - "49.52.27.77:18888"
    # - "49.52.27.77:18889"
    # - "49.52.27.77:18890"
    # - "49.52.27.77:18891"
    # - "49.52.27.77:18892"
    # - "49.52.27.77:18893"
    # - "49.52.27.77:18894"
    # - "49.52.27.77:18895"
    # - "49.52.27.77:18896"
    # - "49.52.27.77:18897"
    balance_mode: round-robin   # load balancing algorithm
partition_files: /home/yssun/proxy_partition/
cache_size: 300000
